### ISSUE TITLE
Run SR Linux as a service for GitHub actions

### ISSUE THREAD

**Issue by vincentbernat** [nokia/srlinux-container-image#5]
Hey!

I am trying to use SR Linux as part of GitHub actions:

```yaml
jobs:
  build-linux:
    services:
      srlinux:
        image: ghcr.io/nokia/srlinux:23.7.1
        ports:
          - 57400:57400
          - 57401:22
        options: "--privileged --user=root"
```

Unfortunately, there is no way to specify a command and the default one for the image is `/bin/bash`. We can specify the entrypoint, but it needs to be a command without arguments. If I pass just `--entrypoint=/opt/srlinux/bin/sr_linux` I don't get the network configuration. The command executed by GitHub is:

```
  /usr/bin/docker create --name 2cfdc039b1784ff78dcfc822f32393b0_ghcrionokiasrlinux2371_816cd6 --label 17eddf --network github_network_c5149df44a6341378dfd86e57bea7c25 --network-alias srlinux -p 57400:57400 -p 57401:22 --privileged --user=root --entrypoint=/opt/srlinux/bin/sr_linux -e GITHUB_ACTIONS=true -e CI=true ghcr.io/nokia/srlinux:23.7.1
```

Maybe the entrypoint could execute `/opt/srlinux/bin/sr_linux` when it detects `GITHUB_ACTIONS=true`?
